### PR TITLE
160 - Display actual file thumbnails

### LINKED ISSUE #160: [Spike - Frontend] Display actual file thumbnails in the Dataset files tab
## Overview of the Feature Request

Show actual File thumbnails within the file tab files. That is, thumbnails retrieved from the Dataverse API.

## What kind of user is the feature intended for?

All users

## What inspired the request?

- [UI feature development process](https://docs.google.com/document/d/1vOSsIGGCbgal4f_lSp1yInQifBcmo5vZ-Z9pfkVDyG4/edit#heading=h.e6y69fx5m61r)

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to Dataverse?

Display actual file thumbnails in the Dataset files tab.

## Any open or closed issues related to this feature request?

- #90

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the functionality to display the actual File Thumbnails on the Files Table. At the same time the File icons used as placeholders for the thumbnails now are correctly displayed depending on the file type.

## Which issue(s) this PR closes:

- Closes #160 

### Changes
1. Get the Files Thumbnails directly from the Data Access API. After discussing with Guillermo we decided not to add this feature to the js-dataverse module.
2. Get the MimeTypeFacets.property file from the Dataverse main repository to correctly map the files mime types to the files icons

### Step 1: Run the development environment
1. Run `npm I`
3. `cd packages/design-system && npm run build`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh 9834-files-api-extension-file-counts`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation

### Step 2: Test Dataset View mode with the implemented changes for the getDatasetFileCounts
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset
4. Upload some files (include some image)
5. From the dataset view mode copy the search parameters from the url. Ex.: `?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT`
6. Go to <http://localhost:8000/spa/datasets> and paste the search parameters. Ex.: <http://localhost:8000/spa/datasets?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT>
8. You are seeing now the same Dataset in the SPA, check that the images thumbnails are correctly display. Also check that the File Icon used as a thumbnail placeholder matches the file type, for example a mp3 should display the Audio File Icon.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No

### CODE REVIEW

**Review by GPortas — CHANGES_REQUESTED** [review]
@MellyGray Obtaining the same error when building the frontend image, as in other PR:

Can you fix it here and check other PRs that may be affected too?

ERRbuildimg

**Comment by MellyGray** [comment]
@GPortas I fixed the error here and I'll check now the other branches

**Review by GPortas — COMMENTED** [review]
It works and looks great. Very nice job!

gif

A small detail that I would like to doublecheck with you is the case of the thumbnail for a .yml file that I have uploaded. The thumbnail image looks different in JSF and in the SPA.

SPA

JSF

**Comment by MellyGray** [comment]
@GPortas I fixed the icon for the yml, glad you noticed it. There are 2 types of icons when there is no defined file type in the map, the other and the default icons, I missunderstood JSF code and I thought it was using the default icon, but it was using the other icon. Quick fix

**Review by GPortas — APPROVED** [review]

**Pull request merged**
