### PR TITLE
Functionality behavior changes added to README, waiting on 9783

### PR DESCRIPTION
**Pull request by GPortas**
## What this PR does / why we need it:

Includes a section in the README on functionality behavior changes, with a first change about the files search behavior in the dataset files tab.

## Which issue(s) this PR closes:

N/A

## Special notes for your reviewer:

Including this section is a decision made in the context of: https://github.com/IQSS/dataverse/issues/9813

## Suggestions on how to test this:

N/A

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:

No

## Is there a release notes update needed for this change?:

No

## Additional documentation:

https://github.com/IQSS/dataverse/issues/9813

### CODE REVIEW

**Comment by pdurbin** [comment]
> Including this section is a decision made in the context of: [IQSS/dataverse#9813](https://github.com/IQSS/dataverse/issues/9813)

We should wait for the issue/PR above to be merged/closed before merging this README PR, right? Should we add the "Waiting" tag?

Otherwise, yes, it definitely makes sense to explain the change in behavior.

**Comment by GPortas** [comment]
Since we had a common consensus yesterday on how to proceed, I would not block this PR. I decided not to close the issue you mention and instead moved it to "ready for review" in case anyone wants to add anything else before closing @pdurbin.

**Comment by pdurbin** [comment]
The rule I would use is this:

"Merging this PR means it will be deployed to https://beta.dataverse.org and the behavior described in the documentation in this PR can be observed and tested there."

**Comment by GPortas** [comment]
@pdurbin I like that rule. 

So let's wait for the API extension and integration PRs to be merged first. Since the functionality that is described, I mean the complete e2e about the file search/filtering, is not yet completely implemented.

Adding the "Waiting" tag.

**Comment by pdurbin** [comment]
> So let's wait for the API extension and integration PRs to be merged first.

@GPortas sounds fine. Another option could be to add this README change into one of those PRs, the one that will be merged last, I suppose.

**Comment by pdurbin** [comment]
@GPortas can you please remind me which PR needs to be merged first?

**Comment by pdurbin** [comment]
@GPortas let me know this PR is waiting on these (thanks!):

- https://github.com/IQSS/dataverse/pull/9820
- https://github.com/IQSS/dataverse/pull/9783

**Review by pdurbin — APPROVED** [review]
Looks good. Approved. Instead of "Changes in functionality behavior" I would probably pick one, either "Changes in functionality" or "Changes in behavior" but whatever, it's fine.

**Pull request merged**
