### PR TITLE
32 - Add buttons and dropdowns of the design system

### LINKED ISSUE #32: Create the buttons and dropdowns of the design system
## Overview of the Feature Request

We would like to add buttons and dropdown elements of our design system as React components and document them in Storybook. This will make it easier for developers to use and maintain consistent buttons and dropdowns across our applications.

The buttons and dropdowns would be the ones documented in the [Design System Analysis document](https://docs.google.com/document/d/1OxCQO7B-yJaMWRl8EzuflcSmIaCmVSs19aoD83PjPmA/edit#heading=h.8nqu9gh25f0n).

These buttons and dropdowns would be using the Design tokens as SASS variables if applicable. These variables are described in [the document](https://docs.google.com/document/d/1OxCQO7B-yJaMWRl8EzuflcSmIaCmVSs19aoD83PjPmA/edit#heading=h.byjoci5aw2)

## What kind of user is the feature intended for?

This feature is intended for developers who use React to build and test components for our web applications.

## What inspired the request?

Our design system includes a set of buttons and dropdowns that are used consistently across our applications. By creating reusable React components for these elements and documenting them in Storybook, we can provide a centralized and easy-to-use reference for developers.

Some references for the Storybook:

- [Vibe Design System](https://style.monday.com/?path=/docs/foundations-colors--page)
- [Storybook Design System](https://storybook-design-system.netlify.app/?path=/docs/colors--page)
- [More references](https://storybook.js.org/showcase)

## What existing behavior do you want changed?

We want to add a new section to Storybook that displays our buttons and dropdowns as React components. This section should include documentation on how to use each component, as well as examples of how the components can be customized.

## Any brand new behavior do you want to add to Dataverse?

No, this feature request does not introduce any brand new behavior to Dataverse.

## Any open or closed issues related to this feature request?

- https://github.com/IQSS/dataverse-frontend/issues/14

- https://github.com/IQSS/dataverse-frontend/issues/30

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the buttons and dropdown elements of the Dataverse design system as React components having them documented in the Storybook. This will make it easier for developers to use and maintain consistent buttons and dropdowns across the application.

## Which issue(s) this PR closes:

- Closes #32 

## Special notes for your reviewer:

I've used Bootstrap [Button](https://react-bootstrap.netlify.app/components/dropdowns/#rb-docs-content) and [Dropdown](https://react-bootstrap.netlify.app/components/dropdowns/#rb-docs-content) encapsulated in our own component.

I've made some customisation to the Bootstrap CSS styles to match the current styles of the Dataverse JSF frontend. This customisation made me add a css property with the `!important`, which is a bad practice, to override a css style added by Bootstrap js.

I believe this wouldn't be necessary if we used Bootstrap as it is, just changing the theme variables, instead of making a huge customisation. I've assumed we wanted this customisation so the new frontend looks as the one in JSF as specified in the [current Style Guide](https://guides.dataverse.org/en/latest/style/index.html) but let me know if we can stick to Bootstrap styles so I can do the changes to remove the property with the !important

## Suggestions on how to test this:

`npm run storybook`

Go to http://localhost:6006

In the UI section you can see the Button and DropdownButton components with their different states

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
This PR adds the button and dropdown of the Dataverse Design System as specified in the [Analysis doc](https://docs.google.com/document/d/1OxCQO7B-yJaMWRl8EzuflcSmIaCmVSs19aoD83PjPmA/edit#heading=h.32ocvoxblw2)

## Is there a release notes update needed for this change?:
Button and dropdown added to the Design System

## Additional documentation:

- [Design System Analysis](https://docs.google.com/document/d/1OxCQO7B-yJaMWRl8EzuflcSmIaCmVSs19aoD83PjPmA/edit#heading=h.32ocvoxblw2)
- [Current Dataverse Style Guide](https://guides.dataverse.org/en/latest/style/index.html)

### CODE REVIEW

**Comment by mreekie** [comment]
Sprint kickoff:
- resized to 33 to 10 for new sprint

**Comment by pdurbin** [comment]
Overall, this is incredible! 🎉 🚀 

I did make this pull request which I'd like to discuss with @MellyGray 

- #42 

Also, the dropdowns are hidden in the mdx. I'm not sure how to fix that.

**Comment by MellyGray** [comment]
@pdurbin I added a commit to fix the canvas size. I couldn't find a way to do it in MDX or with the Storybook functions so I created a container with a fixed size to encapsulate the stories. Maybe I can give it a second thought in my next task #40 

image

**Review by ekraffmiller — COMMENTED** [review]
Overall looks great! I just had a question about accessibility - I noticed the Button had one accessibility rule marked as 'incomplete' - is that ok? 
Screen Shot 2023-04-05 at 1 28 04 PM

**Comment by MellyGray** [comment]
> Overall looks great! I just had a question about accessibility - I noticed the Button had one accessibility rule marked as 'incomplete' - is that ok?
@ekraffmiller the accessibility test runner cannot determine the color of the button due to the gradient, but we can manually check the base color of the gradient in a page like [constrast checker](https://webaim.org/resources/contrastchecker/)  and it seems to have enough contrast

I added the gradient so the button would look more similar to the current button of Dataverse, but we could also remove the gradient and leave the plain blue color

image

**Comment by pdurbin** [comment]
> I added the gradient so the button would look more similar to the current button of Dataverse, but we could also remove the gradient and leave the plain blue color

I'm confused. I thought we recently decided to use Bootstrap 5 styles without any alteration.

Also, I'm nervous about relying on tools that must be run manually.

I also don't love the idea of seeing "Serious" in a tool and ignoring it.

So perhaps we should restore the original Bootstrap 5 button which, from what I understand, doesn't have a background gradient.

**Comment by MellyGray** [comment]
> I'm confused. I thought we recently decided to use Bootstrap 5 styles without any alteration.

Hi Philip! I may have misunderstood the resolution of the Bootstrap styles thing, what I understood  is that we were going to use Bootstrap 5 styles without any alteration except for the Bootstrap theme variables, to set the primary and secondary color. Because overriding these variables doesn't add more complexity since it's part of the available Bootstrap variables to customize the theme and it doesn't requite changing the CSS. It's just a bunch of variables to make a clean customization 

```
$primary: #337AB7;
$secondary: #E7E7E7;

```
Then there is a third variable which is `$enable-gradients: true;` to apply $primary and $secondary but with a gradient, so I thought we could set it to true so the buttons look more similar to the JSF styles. . But anyway, I can set the variable to false.

Just so we are on the same page, I also changed other theme variables such as the font-family or text-color. Is that ok, or we want to keep everything exactly as plain Boostrap?

> 
> Also, I'm nervous about relying on tools that must be run manually.
> 
> I also don't love the idea of seeing "Serious" in a tool and ignoring it.
> 
> So perhaps we should restore the original Bootstrap 5 button which, from what I understand, doesn't have a background gradient.

I totally agree! I just let the gradient because it was already in the JSF frontend. I can set the variable to false

**Review by ekraffmiller — APPROVED** [review]
looks good, fixes the Accessibility issue

**Comment by kcondon** [comment]
@MellyGray I'm ready to merge but there is a merge conflict that needs to be resolved.

**Comment by MellyGray** [comment]
@kcondon sorry! I'll try to solve the conflicts next time before moving to QA. Did you solve the conflicts? I can't see them anymore

**Pull request merged**
