### PR TITLE
Rich Text WYSIWYG Editor - Design System

### LINKED ISSUE #525: Rich Text WYSIWYG Editor - Design System
**Overview of the Feature Request**
Create a rich text editor within the design system for reuse in various places within the SPA frontend.

**What kind of user is the feature intended for?**
All SPA users

**What inspired the request?**

- SPA Create/Edit Dataset form.
- SPA Create/Edit Collection form.
- https://github.com/IQSS/dataverse-frontend/issues/499

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse/issues/6383
- https://github.com/IQSS/dataverse-frontend/issues/499

### PR DESCRIPTION
**Pull request by g-saracca**
## What this PR does / why we need it:
Adds a new Rich Text Editor component to the design system.

This component is made with Tiptap npm packages.
Tiptap is a headless wrapper around ProseMirror – a toolkit for building rich text WYSIWYG editors, which is already in use at many well-known companies such as New York Times, The Guardian or Atlassian.

**_Cons:_** It does not support markdown as output, the output is html. 
**_Pros:_** 

- It does support [Markdown shortcuts](https://tiptap.dev/docs/examples/basics/markdown-shortcuts).
- Compatible with what dataverse already handles for rich content, that is html.
- Tiptap is headless, that means there is no styling provided so all styles were matched to what the rest of the SPA components look like.

## Which issue(s) this PR closes:

- Closes #525 

## Suggestions on how to test this:
Visual code inspection and [Storybook story](https://646fbe232a8d3b501a1943f3-dvpreauelj.chromatic.com/?path=/story/rich-text-editor--default) manual testing.
The component has 100% unit test coverage as well.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
Screen Shot 2024-10-24 at 10 19 52
Screen Shot 2024-10-24 at 10 11 19

### CODE REVIEW

**Comment by g-saracca** [comment]
@ChengShi-1 empty lines added 👍🏼 , thanks

**Review by ChengShi-1 — APPROVED** [review]
Great! Approve.

**Comment by ofahimIQSS** [comment]
Came across one observation - @ChengShi-1 can you confirm this is expected or a bug:
https://646fbe232a8d3b501a1943f3-dvpreauelj.chromatic.com/?path=/story/rich-text-editor--default 

Steps to Reproduce:
1. Navigate to the WYSIWG Editor
2. Click on Add Link
3. Add: https://www.google.com/ 

Issue: After adding the link, nothing happens (link not generated).

**Comment by ChengShi-1** [comment]
> Came across one observation - @ChengShi-1 can you confirm this is expected or a bug: https://646fbe232a8d3b501a1943f3-dvpreauelj.chromatic.com/?path=/story/rich-text-editor--default
> 
> Steps to Reproduce:
> 
> 1. Navigate to the WYSIWG Editor
> 2. Click on Add Link
> 3. Add: https://www.google.com/
> 
> Issue: After adding the link, nothing happens (link not generated).

Hi Omer! After adding a link, you can type your text, and it will appear blue and clickable. Alternatively, you can type the text first, highlight the words, and then attach the link to those words. Picture attached. 
Screenshot 2024-10-30 at 4 43 16 PM

**Comment by ofahimIQSS** [comment]
Thanks for clarifying @ChengShi-1! - Merging PR

**Pull request merged**
