### PR TITLE
238 - Integration single file download

### LINKED ISSUE #238: Single file download
## Overview of the Feature Request
downloadfile

There is already an endpoint under the access API to download a single file. This endpoint is consumed from JSF. See: https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/FileDownloadHelper.java#L88

We can follow the same approach as for image thumbnails, without using js-dataverse and using direct API call.

## What kind of user is the feature intended for?
SPA users.

## What inspired the request?
- https://github.com/IQSS/dataverse-frontend/issues/191#issuecomment-1759380984

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
Single file download

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/191#issuecomment-1759380984

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This pull request establishes a connection between the file download buttons in the files table rows and the access API for downloading files.

## Which issue(s) this PR closes:

- Closes #238 

## Special notes for your reviewer:
The integration of files tabular data is currently under review:
- https://github.com/IQSS/dataverse-frontend/pull/227

As a result, the tabular files' download options won't appear identical to those in the JSF frontend until the aforementioned pull request is merged. Ideally, PR #227 should be merged into the develop branch before this one so that the tabular download options align with the JSF frontend.

### Step 1: Run the development environment
1. Run `npm I`
3. `cd packages/design-system && npm run build`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation

### Step 2: Test Dataset View mode with the implemented changes to download the files
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset
4. Upload some files to the dataset
5. From the dataset view mode copy the search parameters from the url. Ex.: `?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT`
6. Go to <http://localhost:8000/spa/datasets> and paste the search parameters. Ex.: <http://localhost:8000/spa/datasets?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT>
8. You are currently viewing the same dataset in the SPA. In the files table, locate the "Access File" dropdown on the right of each row. From the dropdown, select the option to download the file and verify that it is successfully downloaded.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No

## Is there a release notes update needed for this change?:
No

### CODE REVIEW

**Comment by GPortas** [comment]
@MellyGray Please, can you resolve conflicts?

**Comment by MellyGray** [comment]
@GPortas conflicts resolved

**Review by GPortas — APPROVED** [review]
Looks good!

downloadsinglefile

**Comment by GPortas** [comment]
https://github.com/IQSS/dataverse-frontend/assets/17010447/1c780e11-c4d2-4741-9493-1194000dca72

**Comment by MellyGray** [comment]
> @MellyGray
> 
> Tabular files work well for both original and archival formats. But when selecting RData the following error appears:
> 
> {"status":"ERROR","code":404,"message":"datafile access error: requested optional service (image scaling, format conversion, etc.) could not be performed on this datafile."}

@GPortas The same error appears in JSF when trying to download a tabular file in RData format. 

I found this in the [documentation](https://guides.dataverse.org/en/latest/installation/prerequisites.html?highlight=rdata):

> The Dataverse Software uses [R](https://cran.r-project.org/) to handle tabular data files. The instructions below describe a minimal R Project installation. It will allow you to ingest R (.RData) files as tabular data and to export tabular data as .RData files. **R can be considered an optional component**, meaning that if you don’t have R installed, you will still be able to run and use the Dataverse Software - but the functionality specific to tabular data mentioned above will not be available to your users.

I think we need to install R in the dev-env if we want to test that feature, although I don't think it's necessary since if the users install that option, it should work as expected

**Comment by GPortas** [comment]
@MellyGray In my opinion the download option in R format should not be rendered if R is not configured in Dataverse. To do this we could use a public setting that allows the SPA to know if R is configured in the Dataverse instance.

It certainly happens that when testing JSF on my localhost, I see that the R option is available, although clicking it does nothing. I think this behavior should not be expected for the user. Even though JSF handles it this way, I think the SPA should use the approach I described above (conditional rendering based on a public setting).

Maybe @scolapasta, @jggautier or @pdurbin can share their thoughts on this and if there is a reason that explains why it is done that way in JSF.

**Review by GPortas — CHANGES_REQUESTED** [review]
By the way, I think the conditional rendering solution I described above should not block the PR at all. Whatever solution we propose, I would implement it in another issue.

For this PR I think we should catch the error that occurs (black screen) when clicking the R option, so that it does nothing (like in JSF) but doesn't break. @MellyGray

**Comment by MellyGray** [comment]
> By the way, I think the conditional rendering solution I described above should not block the PR at all. Whatever solution we propose, I would implement it in another issue.
> 
> For this PR I think we should catch the error that occurs (black screen) when clicking the R option, so that it does nothing (like in JSF) but doesn't break. @MellyGray

@GPortas  I can't handle the error since it's an href. Besides, the same black screen behavior is happening in JSF, so I think it should be okay like this until we decide to implement hiding the RData option if R is not installed.

https://github.com/IQSS/dataverse-frontend/assets/23359572/96f15b4d-9fda-4b01-bc4e-e0f7855da60d

**Review by GPortas — APPROVED** [review]

**Comment by pdurbin** [comment]
> In my opinion the download option in R format should not be rendered if R is not configured in Dataverse.

Yes, @BPeuch and probably others agree with you. That's almost exactly how he worded it:

- https://github.com/IQSS/dataverse/issues/8711

**Pull request merged**
