### PR TITLE
link to Chromatic appIds from README #49

### PR DESCRIPTION
**Pull request by pdurbin**
Overall this PR looks fantastic:

- #113

In this PR, I'm suggesting that we link to our fancy new Chromatic URLs in the README. (I know we can also find the links in PRs and Actions.)

Later we can expand on our use on our use of Chromatic in this issue:

- #26.

### CODE REVIEW

**Review by ekraffmiller — COMMENTED** [review]
The change looks good, but I don't know why just a text change in the readme is causing all the tests to fail? It's a problem in the build of the design system, which is strange.

**Comment by pdurbin** [comment]
Ah, this is the problem @GPortas and I have been talking about today:

```
error during build:
Error: Undefined variable.
   ╷
55 │     "primary": $primary-text-emphasis-dark,
   │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

See https://github.com/IQSS/dataverse-frontend/actions/runs/5126059350/jobs/9220048062?pr=114#step:5:33

@ekraffmiller definitely unrelated to the README, like you said. I'd say this is safe to merge if you're ok with the content change. Up to you. 😄

**Comment by ekraffmiller** [comment]
> Ah, this is the problem @GPortas and I have been talking about today:
> 
> ```
> error during build:
> Error: Undefined variable.
>    ╷
> 55 │     "primary": $primary-text-emphasis-dark,
>    │                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> ```
> 
> See https://github.com/IQSS/dataverse-frontend/actions/runs/5126059350/jobs/9220048062?pr=114#step:5:33
> 
> @ekraffmiller definitely unrelated to the README, like you said. I'd say this is safe to merge if you're ok with the content change. Up to you. 😄

Yes, I saw that in the build. What is the issue that you talked about?  Does it require a change to one of the package.json files? I'd rather not send something to QA that is failing the build.  I tried to recreate it locally by deleting my node_modules files but didn't get the same error.

**Comment by pdurbin** [comment]
Oh, I don't mean we have a solution. I just mean we agree that "Undefined variable" was happening on my laptop. And now we see it in GitHub Actions, apparently.

**Comment by GPortas** [comment]
@pdurbin @ekraffmiller 

Yesterday @MellyGray and I solved the problem with undefined bootstrap variables by using a fixed version. See: https://github.com/IQSS/dataverse-frontend/pull/112/commits/ebfb2215bdb19541956ed82ec37233cf1c372e23

**Pull request merged**
