### PR TITLE
187 - Files table download button

### LINKED ISSUE #187: [Frontend] Files Table Download Button
## Overview of the Feature Request

The goal is to add the Download Button to the Files Table in the Dataset Page view mode. This include the functionality of selecting different files from the table and downloading the selection.

### Mockup of the requested element
Captura de pantalla 2023-10-02 a las 11 11 10

### For tabular data this is a dropdown
Screen Shot 2023-10-05 at 2 49 22 PM

## What inspired the request?

- #63 

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to Dataverse?

- Add the Download Button to the Files Table in the Dataset Page view mode

## Any open or closed issues related to this feature request?

- #63
- #182

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR add the Download Button to the Files Table. (Only the UI with no backend integration yet)

## Which issue(s) this PR closes:

- Closes #187 

## Suggestions on how to test this:
1. Install the necessary dependencies using `npm install`.
5. Build the design system with `cd packages/design-system && npm run build`.
6. Navigate back to the root directory with `cd ../../`.
7. Start Storybook with `npm run storybook`.
8. Visit [the Dataset in the Storybook](http://localhost:6006/?path=/story/pages-dataset--draft-with-all-dataset-permissions) to check that the Download button is being displayed in the Files Table, also check the behaviour about showing the No Selected Files Modal if no files are being selected

### Mockup of the requested element
Captura de pantalla 2023-10-02 a las 11 11 10

### For tabular data this is a dropdown
Screen Shot 2023-10-05 at 2 49 22 PM

## Is there a release notes update needed for this change?:
Download button added to the Files Table UI

### CODE REVIEW

**Review by ekraffmiller — COMMENTED** [review]
Hi Melina, this looks good, my only comment is do we need to add this button to the DatasetFiles-Default story?
JSF UI
Screenshot 2023-10-30 at 3 55 22 PM
DatasetFiles story
Screenshot 2023-10-30 at 3 55 04 PM

**Comment by MellyGray** [comment]
@ekraffmiller Now the default story should display de download button, thx!

**Review by ekraffmiller — APPROVED** [review]
LGTM!

**Comment by GPortas** [comment]
Works good on Storybook!

downloadbutton

Merging

**Pull request merged**
