### PR TITLE
130 - Dataset citation thumbnail

### LINKED ISSUE #130: [Spike - Frontend] Implement Dataset citation thumbnail
### Mockup of the requested element

Show a thumbnail related to one of the uploaded dataset files when available, instead of the blue placeholder icon.

### Mockup of the requested element

dataset_thumbnail

## What inspired the request?

- UI discussion on Dataset work

## What existing behavior do you want changed?

N/A

## Any brand new behavior do you want to add to Dataverse?

- Add Dataset citation thumbnail

## Any open or closed issues related to this feature request?

- Not yet

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the dataset thumbnail logic to the UI. This is not yet connected to the API

## Which issue(s) this PR closes:
- Closes #130 

## Special notes for your reviewer:
This is not yet connected to the API, it will need an API extension to get the dataset thumbnail.

## Suggestions on how to test this:
1. Install the necessary dependencies using `npm install`.
5. Build the design system with `cd packages/design-system && npm run build`.
6. Navigate back to the root directory with `cd ../../`.
7. Start Storybook with `npm run storybook`.
8. Visit the [Dataset Citation section in the Storybook](http://localhost:6006/?path=/story/sections-dataset-page-datasetcitation--default) a new story has been added to show how the thumbnail image will be displayed in the Citation block. 

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
Yes, this PR introduces a user interface change. 

dataset_thumbnail

## Is there a release notes update needed for this change?:
Dataset thumbnail added to the Dataset View Mode

### CODE REVIEW

**Comment by GPortas** [comment]
Shouldn't a thumbnail image be displayed instead of the default image? @MellyGray 

I'm on http://localhost:6006/?path=/story/sections-dataset-page-datasetcitation--with-thumbnail

storybookthumbnail

**Comment by MellyGray** [comment]
@GPortas sorry, that was a last minute change and I mixed things 🙏 fixed now! I also fixed some merge conflicts

**Review by GPortas — APPROVED** [review]

**Comment by GPortas** [comment]
@MellyGray Can you please resolve the conflicts? Thanks!

**Comment by GPortas** [comment]
Looks like we have another issue when building the app for beta testing: https://github.com/IQSS/dataverse-frontend/actions/runs/6732893099/job/18300451474

Can you fix it so we can stabilize develop as you did on the other PR?

Do you know how we can detect this before merging PRs? @MellyGray

**Comment by MellyGray** [comment]
@GPortas I fixed the merge conflicts

Also, both the storybook error and this one was caused by type errors so I added a new step to the Github action and to the precommit to check this type of errors

**Pull request merged**
