### PR TITLE
339 add alerts for create dataset

### LINKED ISSUE #339: Add Alerts of the Create Dataset Form
## Overview of the Feature Request

Add all Alerts related to the Create Dataset Form.
Captura de pantalla 2024-03-11 a las 10 45 40
Captura de pantalla 2024-03-11 a las 10 46 49

## What kind of user is the feature intended for?

This feature is intended for all users.

## What inspired the request?

- Suggestions from the beta proposal labeled as "nice to haves."

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to Dataverse?

Add all Alerts related to the Create Dataset Form.

## Any open or closed issues related to this feature request?

- #316

### PR DESCRIPTION
**Pull request by ekraffmiller**
## Which issue(s) this PR closes:

- Closes #339

## Special notes for your reviewer:
Sometimes the e2e getTotalDatasetsCount() fails, because of this issue: https://github.com/IQSS/dataverse-frontend/issues/294

## Suggestions on how to test this
Review Dataset 'Created' Story, Create a Dataset and check for Validation Alerts for missing required fields, and check for Success message on Dataset Page after dataset is created.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
see mockups in #339

### CODE REVIEW

**Comment by ekraffmiller** [comment]
@MellyGray I added some logic to the submitForm() function to save the "created" state before navigating to the View Dataset page, but I wasn't sure where to use the location hook on that page.  I tried adding it to the DatasetFactory or the DatasetProvider, but the logic seemed a little awkward there. Do you have a idea for where logic like this should go?

**Comment by MellyGray** [comment]
> @MellyGray I added some logic to the submitForm() function to save the "created" state before navigating to the View Dataset page, but I wasn't sure where to use the location hook on that page. I tried adding it to the DatasetFactory or the DatasetProvider, but the logic seemed a little awkward there. Do you have a idea for where logic like this should go?

@ekraffmiller  I would place the logic to read the state from the location hook in the DatasetFactory, simply because it's where we're reading the rest of the navigation parameters. I guess what you mean by 'awkward' is because usually, the Dataset Alerts come from the repository, so we need to pass the state all the way through the repository. That's the part that seems awkward to me. Maybe we can pass the 'created' state to the Dataset.tsx component as a new prop and then use the useAlertContext to add a new Dataset Alert from the Dataset.tsx component instead of from the repository. We could call the useAlertContext in the DatasetFactory component, but then we wouldn't be able to test it individually. I don't have a strong opinion on this

**Comment by ekraffmiller** [comment]
> > @MellyGray I added some logic to the submitForm() function to save the "created" state before navigating to the View Dataset page, but I wasn't sure where to use the location hook on that page. I tried adding it to the DatasetFactory or the DatasetProvider, but the logic seemed a little awkward there. Do you have a idea for where logic like this should go?
> 
> @ekraffmiller I would place the logic to read the state from the location hook in the DatasetFactory, simply because it's where we're reading the rest of the navigation parameters. I guess what you mean by 'awkward' is because usually, the Dataset Alerts come from the repository, so we need to pass the state all the way through the repository. That's the part that seems awkward to me. Maybe we can pass the 'created' state to the Dataset.tsx component as a new prop and then use the useAlertContext to add a new Dataset Alert from the Dataset.tsx component instead of from the repository. Alternatively, we could call the useAlertContext in the DatasetFactory component, but then we wouldn't be able to test it individually. I don't have a strong opinion on this

Thanks @MellyGray, I decided to add a 'created' param to Dataset.tsx, to keep the repository logic simpler

**Review by MellyGray — APPROVED** [review]
LGTM! 🎉

**Review by GPortas — APPROVED** [review]
Looks good!

https://github.com/IQSS/dataverse-frontend/assets/17010447/53d19c6a-2ce6-4b9a-8c8f-76e47dca3c8b

**Pull request merged**
