### PR TITLE
Fix/393 Match api email validation

### LINKED ISSUE #393: Create Dataset: email validation does not match validation in the Dataverse API
**What steps does it take to reproduce the issue?**
Go to Create Dataset form, in Point of Contact email, enter an email address that ends with a non-tld string, for example, 'ellen@test.e' and all the other required fields

- When does this issue occur?
When submitting Create Dataset form
- Which page(s) does it occur on?
Create Dataset
- What happens?
It shows an Alert message about a validation error, but it doesn't say what the error is, and the email field isn't highlighted
Screenshot 2024-05-01 at 3 17 17 PM

In the Network tab, the create fails with 403 and this error message:
```
{
    "status": "ERROR",
    "message": "Validation Failed: Point of Contact E-mail ellen@test.e  is not a valid email address. (Invalid value:edu.harvard.iq.dataverse.DatasetFieldValueValue[ id=null ]).java.util.stream.ReferencePipeline$3@626c7975"
}
```

### PR DESCRIPTION
**Pull request by GermanSaracca**
**What this PR does / why we need it**:
Fixes a mismatch between the email validation of the SPA Dataset creation form and the email validation of the dataverse api.
Also improves the UX to display the alert error banner only when creations fail, with messages specific to both the client-javascript api wrapper and the dataverse api itself (from the latter extracting only the field-related part of the error and not the part of the error related to Java invalid value exceptions).

**Which issue(s) this PR closes**:

Closes #393 

**Special notes for your reviewer**:

**Suggestions on how to test this**:
Enter an invalid email (test@test.e) and check that the error message is displayed below the field.
It is a bit difficult to test the error messages in the banners as the validations are being fulfilled from the form before it is submitted.
One option could be to test locally, modifying the code so that no fields are required within the form and submitting the form, in `useDefineRules.tsx` set the required property to `false`.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
The same error banner is maintained, only now when the user submits the form, if there is an error and this banner appears, it is automatically focused with an specific message about the error.

**_Error thrown from the dataverse api_** 👇
Screenshot 2024-05-20 at 11 01 07

**_Error thrown from the client-javascript api wrapper_** 👇
Screenshot 2024-05-20 at 11 03 05

**_How the error banner is focused_** 👇
_In this example the client-side validations were removed just to show the focus case._
[alert-error-behaviour.webm](https://github.com/IQSS/dataverse-frontend/assets/64560524/3f33ef1a-a518-4be7-904a-2c352a79db59)

**Is there a release notes update needed for this change?**:
No.

**Additional documentation**:
No.

### CODE REVIEW

**Comment by ekraffmiller** [comment]
@GermanSaracca There is still a difference between the form validation and the API validation - from my testing, I think the API validation is requiring that the email address be from a list of top level domains, for example: https://data.iana.org/TLD/tlds-alpha-by-domain.txt.  

  When I try an address that is not in the TLD list, I get an error:
Screenshot 2024-05-23 at 9 23 46 PM
The API uses an apache commons validator: https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/validation/EMailValidator.java#L13
I think it is using this underlying domain validator:
https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/DomainValidator.html

I did some searches and couldn't find a javascript library that does something similar, so I'm not sure the best way to handle this, what do you think?

**Comment by GermanSaracca** [comment]
> @GermanSaracca There is still a difference between the form validation and the API validation - from my testing, I think the API validation is requiring that the email address be from a list of top level domains, for example: https://data.iana.org/TLD/tlds-alpha-by-domain.txt.
> 
> When I try an address that is not in the TLD list, I get an error: Screenshot 2024-05-23 at 9 23 46 PM The API uses an apache commons validator: https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/validation/EMailValidator.java#L13 I think it is using this underlying domain validator: https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/DomainValidator.html
> 
> I did some searches and couldn't find a javascript library that does something similar, so I'm not sure the best way to handle this, what do you think?

Hi @ekraffmiller , your findings are totally correct, there is no Javascript library that does the same validations as the Apache library ( at least not a maintained one ).
One option, would be to hardcode all possible TLDS in the SPA  but I really don like it because they are always changing or new ones are added.
I think this is just a client side validation layer and after receiving the error we are showing in the alert so I think it is enough for the user to know what is happening. What are your thoughts?

**Comment by ekraffmiller** [comment]
> > @GermanSaracca There is still a difference between the form validation and the API validation - from my testing, I think the API validation is requiring that the email address be from a list of top level domains, for example: https://data.iana.org/TLD/tlds-alpha-by-domain.txt.
> > When I try an address that is not in the TLD list, I get an error: Screenshot 2024-05-23 at 9 23 46 PM The API uses an apache commons validator: https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/validation/EMailValidator.java#L13 I think it is using this underlying domain validator: https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/DomainValidator.html
> > I did some searches and couldn't find a javascript library that does something similar, so I'm not sure the best way to handle this, what do you think?
> 
> Hi @ekraffmiller , your findings are totally correct, there is no Javascript library that does the same validations as the Apache library ( at least not a maintained one ). One option, would be to hardcode all possible TLDS in the SPA but I really don like it because they are always changing or new ones are added. I think this is just a client side validation layer and after receiving the error we are showing in the alert so I think it is enough for the user to know what is happening. What are your thoughts?



> > @GermanSaracca There is still a difference between the form validation and the API validation - from my testing, I think the API validation is requiring that the email address be from a list of top level domains, for example: https://data.iana.org/TLD/tlds-alpha-by-domain.txt.
> > When I try an address that is not in the TLD list, I get an error: Screenshot 2024-05-23 at 9 23 46 PM The API uses an apache commons validator: https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/validation/EMailValidator.java#L13 I think it is using this underlying domain validator: https://commons.apache.org/proper/commons-validator/apidocs/org/apache/commons/validator/routines/DomainValidator.html
> > I did some searches and couldn't find a javascript library that does something similar, so I'm not sure the best way to handle this, what do you think?
> 
> Hi @ekraffmiller , your findings are totally correct, there is no Javascript library that does the same validations as the Apache library ( at least not a maintained one ). One option, would be to hardcode all possible TLDS in the SPA but I really don like it because they are always changing or new ones are added. I think this is just a client side validation layer and after receiving the error we are showing in the alert so I think it is enough for the user to know what is happening. What are your thoughts?



> I think this is just a client side validation layer and after receiving the error we are showing in the alert so I think it is enough for the user to know what is happening. What are your thoughts?

Yes, I think so too, it would be very cumbersome to maintain a list in our code.  The new alert messages work very well to inform the user 👍

**Comment by ekraffmiller** [comment]
@GermanSaracca  There are some warnings due to the new lint tests...I know we don't need to fix them all, but maybe this PR could fix the ones related to Create Dataset?
```
/Users/ellenkraffmiller/Documents/GitHub/dataverse-frontend2024/src/sections/create-dataset/CreateDataset.tsx
  44:6  warning  React Hook useEffect has a missing dependency: 'setIsLoading'. Either include it or remove the dependency array  react-hooks/exhaustive-deps

/Users/ellenkraffmiller/Documents/GitHub/dataverse-frontend2024/src/sections/create-dataset/MetadataBlockFormFields/MetadataFormField/Fields/PrimitiveMultiple.tsx
  51:5  warning  React Hook useMemo has a missing dependency: 'builtFieldNameWithIndex'. Either include it or remove the dependency array  react-hooks/exhaustive-deps
```

**Comment by GermanSaracca** [comment]
I completely agree, I will fix those eslint warnings, thanks @ekraffmiller

**Review by ekraffmiller — APPROVED** [review]
LGTM!

**Review by GPortas — APPROVED** [review]
LGTM

https://github.com/IQSS/dataverse-frontend/assets/17010447/ab384df4-32aa-4aa2-8011-575a2181c217

**Pull request merged**
