### PR TITLE
221 - Integration multiple files download

### LINKED ISSUE #221: Files Table row selection Download Button
## Overview of the Feature Request
Integrate the Download button from the Files Table to actually download the selected files.

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- https://github.com/IQSS/dataverse-frontend/issues/187

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
Be able to download the selected files using the Download button in the Files Table

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/187

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the integration of the Download multiple files button in the Files Table with the dataverse API. With this integration the SPA user will be able to select multiple files from the dataset table and download them.

## Which issue(s) this PR closes:

- Closes #221 

### Step 1: Run the development environment
1. Run `npm I`
3. `cd packages/design-system && npm run build`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation

### Step 2: Test Dataset View mode with the implemented changes to download the files
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset
4. Upload some files to the dataset
5. From the dataset view mode copy the search parameters from the url. Ex.: `?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT`
6. Go to <http://localhost:8000/spa/datasets> and paste the search parameters. Ex.: <http://localhost:8000/spa/datasets?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT>
8. You are currently viewing the same dataset in the SPA. In the files table, locate the "Download" button on the right of the Files Table. Select some files using the checkboxes and then click the Download button to download all of them at once.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No

## Is there a release notes update needed for this change?:
No

### CODE REVIEW

**Comment by GPortas** [comment]
Can you please resolve conflicts? @MellyGray

**Comment by MellyGray** [comment]
@GPortas merge conflicts resolved

**Review by GPortas — CHANGES_REQUESTED** [review]
Downloading multiple files works fine. The message saying that the zip download limit has been exceeded is confusing, although I understand that it appears because the integration of the zip limit setting is pending, and the limit (1B) is mocked, right?

On the other hand for downloading a single file, a zip should not be generated, and the file must be downloaded individually unzipped, as in JSF. 

https://github.com/IQSS/dataverse-frontend/assets/17010447/402701e3-5ae7-44e0-b3ab-9ae4a62c19f1

**Comment by MellyGray** [comment]
@GPortas

1. I can increase the mock from 1B zip limit to something higher so it doesn't appear in beta
2. I don't understand why is downloading 1 file as a zip, I saw this comment in JSF 
 ```
 // There's a chance that this is not really a batch download - i.e.,
  // there may only be one file on the downloadable list. But the fileDownloadService
  // method below will check for that, and will redirect to the single download, if
  // that's the case. -- L.A.
  fileDownloadService.writeGuestbookAndStartBatchDownload(guestbookResponse, doNotSaveGuestbookResponse);
```

If you look at the implementation if `(fileIds.length == 1) { ` it calls `redirectToDownloadAPI()` for the **single file download** instead of   `settingsService.getValueForKey(SettingsServiceBean.Key.CustomZipDownloadServiceUrl);` to get the zip. Is the API not using this same `fileDownloadService` than JSF?

I mean, I can handle it in the frontend and call the single download from the frontend, but isn't the desired API behavior to download a single file if only 1 file is selected? I want to be sure before applying the logic in the UI

**Comment by MellyGray** [comment]
@GPortas I applied the requested changes

**Review by GPortas — APPROVED** [review]
LGTM

**Pull request merged**
