### PR TITLE
295 - Display real dataset version information in the File Page

### LINKED ISSUE #295: Display real dataset version information in the File Page
## Overview of the Feature Request
The js-dataverse module GetFile use case it's going to be extended to retrieve the dataset version information needed to display it in the File Page. We need to integrate the module changes with the SPA. Currently we're using mock data for the dataset version information so it would be just replacing this mock data by the real dataset version information retrieved by the module.

This issues depends on:
https://github.com/IQSS/dataverse-client-javascript/issues/123

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- https://github.com/IQSS/dataverse-client-javascript/issues/123

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
Display real dataset version information in the File Page

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/283

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the integration with js-dataverse to get the dataset version information from the getFile use case to display the data in the SPA File Page

## Which issue(s) this PR closes:

- Closes #295 

### Step 1: Run the development environment
1. Run `npm I`
3. `cd packages/design-system && npm run build`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation

### Step 2: Test breadcrumbs
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
4. Create a new Dataset
5. Upload a file to the dataset
7. Go to <http://localhost:8000/spa> and select your dataset in the list
8. From the list of files in the Dataset page select your file to go to the File page
9. In the File Page check that the dataset version information such as the version labels and dataset citation matches the real dataset version information

### CODE REVIEW

**Review by GPortas — COMMENTED** [review]
Looks good overall!

Here I share a couple of UI details that should be fixed to match the JSF version:

spa

Here is the JSF version:

jsf

**Comment by MellyGray** [comment]
> Looks good overall!
> 
> Here I share a couple of UI details that should be fixed to match the JSF version:

@GPortas, I have updated the download URL, thank you.

However, regarding the date, I believe we all agreed some time ago to use the local standard for dates in the UI instead of the international ISO format. Therefore, in your case, you're seeing the Spanish standard date format, which will differ for US users. However, even for US users, it will not match the JSF format, because we are now using the local format instead of the international ISO format. The same thing is happening in any SPA date

**Comment by GPortas** [comment]
@MellyGray Can you please resolve the conflicts?

**Review by GPortas — APPROVED** [review]
LGTM

**Pull request merged**
