### PR TITLE
138 - Files table UI [2/2] - Sorting

### LINKED ISSUE #138: [Spike - Frontend] [2/2] Create the File Tab of the Dataset - Sorting
## Overview of the Feature Request

Add the sorting selector UI at the top to the Files Table
image

## What kind of user is the feature intended for?

Developers

## What inspired the request?

- #105

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to Dataverse?

Add the sorting selectors UI at the top to the Files Table

## Any open or closed issues related to this feature request?

- #105

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the use case and the UI component for the sorting selection of the Files Table.

## Which issue(s) this PR closes:

- Closes #138 

## Special notes for your reviewer:
This is only the UI, no backend connected yet. You can see the getFiles use case modified to accept some criteria and the UI component for this criteria selectors

I had to do some changes to the design system, in order to use the Dropdown component as a selector.

## Suggestions on how to test this:

1. `npm i`
2. `cd packages/design-system && npm run build`
3. cd back to the root 
4. `npm run storybook`
5. See the sort selector in the localhost:6006 storybook in the Dataset page, you can select different sort options

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
image

## Is there a release notes update needed for this change?:
Added SortBy selector to the Files Table

### CODE REVIEW

**Review by GPortas — COMMENTED** [review]
The code looks good, and I have tested Storybook and works as expected!

Dataset with files:
storybook_dataset_with_files

Dataset with no files:
storybook_dataset_with_no_files

Let's stabilize the base branch ([feature/104-create-the-file-table](https://github.com/IQSS/dataverse-frontend/tree/feature/104-create-the-file-table)), resolve conflicts and then we can move it to QA @MellyGray.

**Comment by pdurbin** [comment]
This PR has merge conflicts.

**Comment by MellyGray** [comment]
Merge conflicts fixed! @GPortas

**Review by GPortas — APPROVED** [review]

**Comment by kcondon** [comment]
@MellyGray I see the sort control and it orders things but not in the way I have selected. For example A-Z changes the arrangement of files but the filenames are not ordered. 
Screen Shot 2023-07-31 at 4 34 45 PM

**Pull request merged**
