### PR TITLE
125 - Integration dataset summary continued

### LINKED ISSUE #125: [Spike - Integration] Dataset summary, continued
## Overview of the Feature Request
Spike issue for the integration of the frontend work (UI) of issue #115 with the js-dataverse implementation of these use cases

- https://github.com/IQSS/dataverse-client-javascript/issues/63
- https://github.com/IQSS/dataverse-client-javascript/issues/64
- https://github.com/IQSS/dataverse-client-javascript/issues/66

## What kind of user is the feature intended for?

All

## What inspired the request?
- #115 

## What existing behavior do you want changed?
Integrate UI with the js-dataverse implementation

## Any open or closed issues related to this feature request?
- #115

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR integrates the latest changes from the js-dataverse module regarding the Dataset Summary continue spike #125 

This changes includes:

- https://github.com/IQSS/dataverse-client-javascript/issues/63
- https://github.com/IQSS/dataverse-client-javascript/issues/64
- https://github.com/IQSS/dataverse-client-javascript/issues/66

## Which issue(s) this PR closes:

- Closes #125 

## Special notes for your reviewer:
During the integration of the getMetadataBlockByName use case I found that there were some changes needed to correctly display the MetadataBlockFields in the Dataset view mode. These include correctly displaying the [displayFormat variables](https://guides.dataverse.org/en/4.20/admin/metadatacustomization.html#displayformat-variables)

### Step 0: Get a personal token to use the js-dataverse registry
1. create a copy of `.npmrc.example` file without the .example suffix
2. go to https://github.com
3. Click your profile image
4. Go to settings
5. In the lateral bar click Developer Settings
6. In the lateral bar click Personal Access Tokens and select Tokens(classic)
7. Click Generate new token (classic)
8. Add a name to your new token
9. Select read:packages check
10. Click Generate token button
11. Copy your token
12. Substitute your new token in the .npmrc file
14. To check if it works run `npm i`

### Step 1: Run the development environment
1. Run `npm I`
2. `cd packages/design-system && npm run build`
3. `cd ../../`
4. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
5.  `cd dev-env`
6. `./run-env.sh develop`
7. To check the environment go to <http://localhost:8000> and check your local dataverse installation

### Step 2: Test Dataset View mode with the implemented changes for the getMetadataBlockByName
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset
4. From the dataset view mode copy the search parameters from the url. Ex.: `?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT`
5. Go to <http://localhost:8000/spa/datasets> and paste the search parameters. Ex.: <http://localhost:8000/spa/datasets?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT>
6. You are seeing now the same Dataset in the SPA, check that all the data is displayed correctly regarding the Metadata Block Fields. The displayFormat is being read from the tsv definitions

### Step 2: Test publicationDate
1. Go to <http://localhost:8000> and look for you newly created Dataset, go and publish it
2. Go back to <http://localhost:8000/spa/datasets?persistentId=doi:10.5072> and in the Metadata tab check the publication date.

To test citationDate and alternativePersistentId perform the actions required in the dataset from http://localhost:8000 then check these fields in the same dataset at http://localhost:8000/spa

### CODE REVIEW

**Comment by GPortas** [comment]
@MellyGray Please, can you resolve the conflicts?

**Review by GPortas — COMMENTED** [review]
I have tested the citation metadata for a published dataset with no citation date set, and the metadata fields are the same as in JSF.

JSF:

jsf_citation

SPA:

spa_citation

The email should be hidden, but a separate issue has already been created to change this.

I created another dataset, published it and set the citation date via this [endpoint](https://guides.dataverse.org/en/latest/api/native-api.html?highlight=dateofdeposit) of the API guide. When accessing the SPA Dataset page the following error appears:

citation_date_err

I haven't found a direct way to test alternativePersistentId, have you tested this field before?

**Comment by MellyGray** [comment]
@GPortas 

> I have also created another dataset, published it and set the citation date via [**Set Citation Date Field Type for a Dataset** endpoint](https://guides.dataverse.org/en/latest/api/native-api.html?highlight=dateofdeposit) of the API guide. When accessing the SPA Dataset page the following error appears:

Sorry, there was an error when the citationDate is undefined. I added a commit to fix it

> I haven't found a direct way to test alternativePersistentId, have you tested this field before?
Nope, I talked with Kevin about this, apparently it references another PID when the dataset is allocated in a different place, but I don't know how to upload a dataset to a different place. I was trusting that if it's in the js-dataverse response then it would show up in the page as the rest of the metadata. We can ask in the frontend channel how to test this

**Comment by GPortas** [comment]
> @GPortas
> 
> > I have also created another dataset, published it and set the citation date via [**Set Citation Date Field Type for a Dataset** endpoint](https://guides.dataverse.org/en/latest/api/native-api.html?highlight=dateofdeposit) of the API guide. When accessing the SPA Dataset page the following error appears:
> 
> Sorry, there was an error when the citationDate is undefined. I added a commit to fix it
> 
> > I haven't found a direct way to test alternativePersistentId, have you tested this field before?
> 
> Nope, I talked with Kevin about this, apparently it references another PID when the dataset is allocated in a different place, but I don't know how to upload a dataset to a different place. I was trusting that if it's in the js-dataverse response then it would show up in the page as the rest of the metadata. We can ask in the frontend channel how to test this

@MellyGray Thanks!

I'm wondering if it makes sense to cover the case of the undefined value with some test, since I have seen in your commit that you have not updated the tests with your fix.

On the other hand, I wouldn't worry too much about alternativePersistentId, as long as its optional appearance is covered with tests.

**Comment by MellyGray** [comment]
@GPortas 

> I'm wondering if it makes sense to cover the case of the undefined value with some test, since I have seen in your commit that you have not updated the tests with your fix.

I tried to add the test, but when I do this flow with the UI `create dataset>publish> set depositdate as the citation date with the API `then the citationDate is undefined 

But when I do the same in my integration tests create `dataset>publish> set depositdate as the citation date with the API` the citationDate is not undefined 

So I can't reproduce the undefined in my tests, I have no idead why, because the API response is the same in the tests `message "Citation Date for dataset :persistentId set to: Deposit Date"`

So I decided not to leave that test because it's not reproducing the error anyways

> On the other hand, I wouldn't worry too much about alternativePersistentId, as long as its optional appearance is covered with tests.

I don't have unit tests for the file JSDatasetMapper.ts, so I only test this file with the integration tests, therefore if I cannot reproduce the alternativePersistentId via de API in the integration tests, then I cannot test if that condition is correct, that's what happened with the citationDate

**Comment by MellyGray** [comment]
@GPortas I added some unit tests for the JSDatasetMapper to test the citationDate and alternativePersistentId as requested

**Comment by kcondon** [comment]
@MellyGray Seeing an error when I run npm -i:

npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://npm.pkg.github.com/download/@IQSS/dataverse-client-javascript/2.0.0-pr80.378cc1e/2361fc91f5e8618751025871e860062307b1adf4 - authentication token not provided

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/kcondon/.npm/_logs/2023-09-11T18_06_14_080Z-debug-0.log
HMDC-C02DL1LVMD6P:dataverse-frontend kcondon$ pwd

**Comment by kcondon** [comment]
Thanks, my token had expired and I also forgot how to do that step.

**Pull request merged**
