### PR TITLE
283 - Display real file metadata in the File Page

### LINKED ISSUE #283: Display real file information in the File Page
## Overview of the Feature Request
Implement the `FileRepository.getById` method using js-dataverse use case to display real file information in the File Page. This means implementing the File Page e2e

Take into account that the file information is split into several use cases in js-dataverse. To complete the file page information you'll need the getFile, getFileCitation and getFileUserPermissions use cases.

For the moment we are going to display only the getFile and getFileUserPermissions information. We can leave the citation mocked until the API is extended to retrieve the citation

This issue depends on this one from js-dataverse to implement getFile use case:
- https://github.com/IQSS/dataverse-client-javascript/issues/115

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- https://github.com/IQSS/dataverse-frontend/issues/249

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
Display real file information in the File Page

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/249

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the integration of the File Page UI with the js-dataverse GetFile use case to display the actual file metadata in the File Page.

## Which issue(s) this PR closes:

- Closes #283 

## Special notes for your reviewer:
I removed FileVersion from the File model since files do not have versions, they only have the dataset version

During the development of the feature we realised that the GetFile use case doesn't retrieve dataset version information which is needed in the File Page. That's why we created a new issue to extend the API to include this information in the payload.

- https://github.com/IQSS/dataverse/issues/10280

This means that the dataset information displayed in the File Page is mocked data.

The same happens with the citation information. An API extension is needed to get the file citation:

- https://github.com/IQSS/dataverse/issues/10240

This data will be included in future iterations

### Step 1: Run the development environment
1. Run `npm I`
3. `cd packages/design-system && npm run build`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation

### Step 2: Test File Page
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset
4. Upload some files to the dataset
5. From the dataset view mode click on some file to go to the File Page in JSF
6. From the url copy the fileId number
7. Go to <http://localhost:8000/spa/files> and paste the fileId number as an id query param. Ex.: <http://localhost:8000/spa/files?id=212121>
8. It's also possible to access a draft version of the file Ex.: <http://localhost:8000/spa/files?id=212121&datasetVersion=DRAFT>
8. You are currently viewing the same file in the SPA. Remember that only the file title and file metadata are being retrieved by the API the citation and dataset information is mocked data.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No
## Is there a release notes update needed for this change?:
No

### CODE REVIEW

**Review by M27Mangan — CHANGES_REQUESTED** [review]
Changes look good! Chromatic seems to be working as-expected as well with not flagging new UI elements. 

Just need to fix merge conflicts as discussed on todays meeting, which is why I've flagged as "Request Changes".

**Comment by MellyGray** [comment]
@M27Mangan I fixed the conflicts!

**Comment by MellyGray** [comment]
@M27Mangan there are conflicts again from the latest merge, I'll assign the issue to myself again to fixe the merge conflicts

**Comment by M27Mangan** [comment]
@MellyGray It seems like there were new merge conflicts for the test file, can you fix those and Slack me when you've committed again so I can approve before another branch gets merged? :)

**Review by M27Mangan — APPROVED** [review]
Approved! Thank you!

**Review by GPortas — APPROVED** [review]
Looks good!

https://github.com/IQSS/dataverse-frontend/assets/17010447/383d81a4-dda4-4396-a256-e7012518e6b4

**Pull request merged**
