### PR TITLE
52 - Coverage with cypress

### LINKED ISSUE #52: Replace in the coverage check Vitest by Cypress component testing
## Overview of the Feature Request

Replace in the current coverage check Vitest runner by Cypress component testing runner so it continues working once we migrate the unit tests from Vitest to Cypress Component Testing as decided in the [testing tools analysis](https://github.com/IQSS/dataverse-frontend/issues/27)

## What kind of user is the feature intended for?
Dataverse frontend developers and QA

## What inspired the request?
- https://github.com/IQSS/dataverse-frontend/issues/27

## What existing behavior do you want changed?
Replace Vitest by Cypress component testing in the coverage check command both in the pre-commit and in the Github action.

## Any brand new behavior do you want to add to Dataverse Frontend?
None

## Any related open or closed issues to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/47
- https://github.com/IQSS/dataverse-frontend/issues/19

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds a test coverage mechanism which generates a /coverage/lcov.info file and uploads it to [Coveralls](https://coveralls.io/github/IQSS/dataverse-frontend)

There was already a coverage check, but since we migrated the unit tests to Cypress Component testing we had to run the coverage tests against these cypress component tests.

## Which issue(s) this PR closes:

- Closes #52 

## Special notes for your reviewer:
I moved the cypress tests to the /tests folders and removed the vitest tests a part from setting the coverage

## Suggestions on how to test this:
npm run test:unit

npm run test:coverage

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No

## Is there a release notes update needed for this change?:
No

### CODE REVIEW

**Comment by MellyGray** [comment]
⚠️  This PR is ready for review but I wanted to keep it as a draft because we can't merge this right now. To merge this we first need to:

1. Merge all the design system components
2. Create a new issue to create all the cypress tests for all the new components
3. Then we can merge this cypress coverage check

**Comment by MellyGray** [comment]
> As discussed at standup just now we especially need this:
> 
> "Create a new issue to create all the cypress tests for all the new components"
> 
> One that issue has been created and a PR for it merged, we will be able to merge this PR about coverage.
> 

issue created! 
- #76

**Comment by pdurbin** [comment]
Thank you, @MellyGray!

**Review by ekraffmiller — COMMENTED** [review]
I ran it locally and it looks great!  I noticed in the github action, that it had a link to the coveralls website that isn't working.  Is that supposed to work, or is it something that we need to pay extra for?
Screenshot 2023-05-04 at 7 56 00 AM

**Comment by MellyGray** [comment]
@ekraffmiller that's strange, the link for the job is working for me and I'm not logged in

image

**Comment by ekraffmiller** [comment]
> @ekraffmiller that's strange, the link for the job is working for me and I'm not logged in
> 
I'm sorry, that was my fault! I clicked on the first link, that didn't include the job number in the url. The second link worked for me 👍

**Review by ekraffmiller — APPROVED** [review]
LGTM

**Comment by pdurbin** [comment]
@MellyGray can you please resolve the merge conflicts?

**Comment by pdurbin** [comment]
@MellyGray thanks for resolving the merge conflicts!

This is very cool. One question I have: how can I tell which lines are not covered? For example, 20% of lines are apparently not covered in Tabs.tsx (screenshots below). Which ones? Coveralls says "source not available".

Screenshot 2023-05-05 at 12-40-30 Coveralls io - Test Coverage History and Statistics

Screenshot 2023-05-05 at 12-40-49 Coveralls io - Test Coverage History and Statistics

By contrast, for Dataverse I can see green (covered) vs. red (uncovered) lines here, for example: https://coveralls.io/builds/59676269/source?filename=src%2Fmain%2Fjava%2Fedu%2Fharvard%2Fiq%2Fdataverse%2Fdatavariable%2FVarGroup.java

Screenshot 2023-05-05 at 12-46-41 Coveralls io - Test Coverage History and Statistics

**Comment by MellyGray** [comment]
> @MellyGray thanks for resolving the merge conflicts!
> 
> This is very cool. One question I have: how can I tell which lines are not covered? For example, 20% of lines are apparently not covered in Tabs.tsx (screenshots below). Which ones? Coveralls says "source not available".
> 

I see, that's strange, are you using [coverallsapp/github-action@v2](https://github.com/coverallsapp/github-action) too in the dataverse repo? Maybe I didn't configure it well, but it doesn't seem to ask anything apart from the `lcov.info` file

In any case, I am not worried about the uncovered lines as they can be checked locally in the coverage/lcov-report/index.html file. However, we could create a new issue to address the source not available issue, so that it does not delay the merging of this pull request any further.

**Comment by pdurbin** [comment]
It's weird. I AM logged in with GitHub. 😄 

I even made myself and admin on the repo, logged out and back into GitHub. Nothing.

More importantly, we shouldn't move this to QA yet because the following PR is targeting this PR (instead of "develop"), right?

- https://github.com/IQSS/dataverse-frontend/pull/81

**Comment by pdurbin** [comment]
Oh, I have to be logged in to Coveralls, not GitHub, to see the frontend repo, but not the main repo. Very strange.

Yes, after logging in to Coveralls (with my GitHub credentials), I can see the source for that file I was looking at before: https://coveralls.io/builds/59669530/source?filename=src%2Fsections%2Fui%2Ftabs%2FTab.tsx

Here's a screenshot:

Screen Shot 2023-05-08 at 5 09 44 PM

Again, it's strange that I don't have to log in to Coveralls to see (for example) https://coveralls.io/builds/59676269/source?filename=src%2Fmain%2Fjava%2Fedu%2Fharvard%2Fiq%2Fdataverse%2Fdatavariable%2FVarGroup.java

It even works in an incognito/private window:

Screen Shot 2023-05-08 at 5 13 03 PM

**Comment by MellyGray** [comment]
I can see the source files now without being logged in. Did you change something? Cause I didn't. But now I can see the source files without being logged in. Maybe when I did the first log in I gave read permissions to Coveralls and now anyone can see the source files? 

image

**Comment by pdurbin** [comment]
@MellyGray I reached out on the issue you linked and @afinetooth helped us out (thanks!): https://github.com/lemurheavy/coveralls-public/issues/1579#issuecomment-1539224303

**Comment by kcondon** [comment]
[like]  Condon, Kevin M reacted to your message:
________________________________

**Pull request merged**
