### PR TITLE
Upgrade to v4 download and upload artifacts

### LINKED ISSUE #537: Stop using v3 of download-artifact and upload-artifact
We need to update `download-artifact` and `upload-artifact` to latest 4 version.

`upload-artifact` is used in:

- deploy.yml
- deploy-beta-testing.yml
- test.yml

`download-artifact` is used in:

- deploy.yml
- deploy-beta-testing.yml

From https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

"Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible. While v4 of the artifact actions improves upload and download speeds by up to 98% and includes several new features, there are [key differences](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) from previous versions that may require updates to your workflows. Please see [the documentation](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) in the project repositories for guidance on how to migrate your workflows."

### PR DESCRIPTION
**Pull request by g-saracca**
## What this PR does / why we need it:
Updates download and upload artifacts to version 4.
upload-artifacts have been updated in the following workflows:

- deploy.yml
- deploy-beta-testing.yml
- test.yml

download-artifacts have been updated in the following workflows:

- deploy.yml
- deploy-beta-testing.yml

## Which issue(s) this PR closes:

- Closes #537 

## Suggestions on how to test this:
Visual code inspection and re-run the **_test_** action. 
`deploy.yml` workflow has not been used.
`deploy-beta-testing.yml` workflow has been already tested deploying this current branch and it can be checked again after merging this branch into develop.

**_Note:_** the code coverage (coverall report) says it has decreased but it is the same rare problem that keeps occurring sometimes, we should not worry about it on this issue.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No

## Is there a release notes update needed for this change?:
No

## Additional documentation:
No

### CODE REVIEW

**Review by stevenwinship — COMMENTED** [review]
In dataverse project we had to use v4.1.7. Is there a reason not to use this instead of v4?

        # using v4.1.7 due to a bug in v4
        uses: actions/download-artifact@v4.1.7

**Comment by g-saracca** [comment]
> In dataverse project we had to use v4.1.7. Is there a reason not to use this instead of v4?
Hi @stevenwinship, thanks! I thought using only v4 would always point to the latest version 4, but it might be safer to use an exact version, could you also tell me what exact version you are using for the upload-artifact?

**Comment by pdurbin** [comment]
> I thought using only v4 would always point to the latest version 4

It's very confusing. https://github.com/orgs/community/discussions/25248#discussioncomment-3247083 by @ethomson (hi, Edward! 👋 ) says, "we only match a literal release tag".

However the GitHub Actions Toolkit docs at https://github.com/actions/toolkit/blob/master/docs/action-versioning.md#versioning say, "Binding to a major version is the latest of that major version ( e.g. v1 == "1.*" )" Then it goes on to say this:

"Make the new release available to those binding to the major version tag: Move the major version tag (v1, v2, etc.) to point to the ref of the current release."

So it might depend on if people are using GitHub Actions Toolkit or not? I'm not sure.

**Comment by pdurbin** [comment]
@ethomson thanks for getting back to us so fast! Does this mean that for any action we can't know if the author is making updates to the "major version tag" or not? We have to poke around?

For example, when I look at the "download-artifact" action, I'm (now) fairly confident that "v4" means "latest 4" by looking at the following:

- The latest release is https://github.com/actions/download-artifact/releases/tag/v4.1.8 and came out on July 5th.
- If I manually navigate to https://github.com/actions/download-artifact/releases/tag/v4 ("v4" doesn't appear in the listing), the sha matches v4.1.8 (fa0a91b) as does the date (July 5th).

**Review by stevenwinship — DISMISSED** [review]

**Comment by ethomson** [comment]
> @ethomson thanks for getting back to us so fast! Does this mean that for any action we can't know if the author is making updates to the "major version tag" or not? We have to poke around?

I think that you do. And there's a few cases here: the author does this _always, and reliably_, the author never does this, or the author has a manual process to do this when they publish and maybe sometimes forgets.

I think that GitHub is pretty good about always updating the major version tag for their actions. (Hopefully automated, or at least tested; I honestly don't remember.) But me, personally, I'm in the latter camp and sometimes forget. 😢

**Comment by ofahimIQSS** [comment]
It looks like test / component (pull_request) is failing - https://github.com/IQSS/dataverse-frontend/actions/runs/11862443295/job/33392252664?pr=550

**Review by ofahimIQSS — APPROVED** [review]
changes look good

**Pull request merged**
