### PR TITLE
315 - Developer guide: Architecture design methodology

### LINKED ISSUE #315: [Spike - Developer Guide] Breakdown of architecture design methodology
## Overview of the Feature Request

Create the first section of the developer guide: _Breakdown of architecture design methodology_

This issue is a spike created from https://github.com/IQSS/dataverse-frontend/issues/304 to narrow the scope a little and be able to better prioritize it.

## What kind of user is the feature intended for?
Developers.

## What inspired the request?
- https://github.com/IQSS/dataverse-frontend/issues/304

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse?
N/A

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-frontend/issues/304

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds a new section to the Developer Guider about the Architecture design methodology

## Which issue(s) this PR closes:

- Closes #315 

## Suggestions on how to test this:
Go to the DEVELOPER GUIDE and check [the new section](https://github.com/IQSS/dataverse-frontend/blob/315-feat-developer-guide-architecture-design-methodology/DEVELOPER_GUIDE.md#breakdown-of-architecture-design-methodology).

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No
## Is there a release notes update needed for this change?:
New section to the Developer Guider about the Architecture design methodology

### CODE REVIEW

**Review by ekraffmiller — DISMISSED** [review]
Looks good! Thank you @MellyGray!

**Comment by pdurbin** [comment]
@MellyGray heads up that there are merge conflicts.

**Comment by ekraffmiller** [comment]
reviewed again after merge, looks good 👍

**Review by ekraffmiller — APPROVED** [review]
LGTM

**Pull request merged**
