### PR TITLE
159 - Manage File User Permissions for the Files Tab

### LINKED ISSUE #158: Manage user permissions for the conditional rendering
## Overview of the Feature Request
In the Dataset View Mode there are some elements that are conditionally rendered depending on different user permissions. We need to manage these permissions in the frontend and add the conditions to these elements.

- [x]  #159 

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- https://github.com/IQSS/dataverse-client-javascript/pull/80 The getFileUserPermissions use case

## What existing behavior do you want changed?
Render some elements of the Dataset View Mode depending on the user permissions

## Any brand new behavior do you want to add to Dataverse?
None

## Any open or closed issues related to this feature request?
- #139

### LINKED ISSUE #159: [Spike - Frontend] Manage user permissions for the conditional rendering
## Overview of the Feature Request

Implement the UI logic for #158 

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- #158 

## What existing behavior do you want changed?
Render some elements of the Dataset View Mode depending on the user permissions

## Any brand new behavior do you want to add to Dataverse?
None

## Any open or closed issues related to this feature request?
-  #158

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the management of the file user permissions for the  the Files Tab.

## Which issue(s) this PR closes:

- Closes #159 

### Changes
1. Two new useCases added to manage the file permissions checkFileDownloadPermission and checkFileEditDatasetPermission. Note: The checkFileEditDatasetPermission at the file level may be replaced in the future by a checkDatasetEditPermission at the dataset level but since in the js-dataverse implementation the editDataset permission can only be retrieved using a file, that's what have been implemented in the UI.
2. The File model has been refactored to remove the canDowload property since this property is actually a permission instead of a property of the resource. This affects most of the changed code
3. A FilePermissionsProvider has been added to globally manage the file permissions in the application

## Suggestions on how to test this:
To test this from a UI perspective, the Files Tab elements in the Storybook should continue being displayed as in the previous PRs, this is because in previous PRs the permissions were hardcoded and now they have been implemented with their own use cases. So basically the testing consists on checking that everything is being displayed in the Files Table as it was before, for example as it was working in the [feature/139-files-table-file-action-buttons-ui](https://github.com/IQSS/dataverse-frontend/tree/feature/139-files-table-file-action-buttons-ui) branch

1. `npm i`
8. `cd packages/design-system && npm run build`
9. `cd ../../`
10. `npm run storybook`
11. Check the Dataset Page and the stories in Sections/Dataset Page/DatasetFiles/

## Is there a release notes update needed for this change?:
No

### CODE REVIEW

**Review by pdurbin — APPROVED** [review]
I'm approving this. I didn't do any particular testing apart from getting the section to load in story book.

I looked through the diff of just this PR (which merges into non-develop) at https://github.com/IQSS/dataverse-frontend/compare/feature/139-files-table-file-action-buttons-ui...feature/159-manage-user-permissions-files

I forget if I asked this already, but I still wonder why it's called DatasetMother. I wonder if it should be DatasetParent instead.

Also, it's weird to me that there are 200 total files in Storybook and somehow within that small number there are 100K embargoed files. 😄 

Screen Shot 2023-09-11 at 3 06 38 PM

**Comment by kcondon** [comment]
@MellyGray I actually had trouble loading this in Storybook. I saw two blank pages:

Screen Shot 2023-09-11 at 4 15 10 PM

**Comment by GPortas** [comment]
@pdurbin For any class you see with the "Mother" suffix, it is a naming convention for classes used in testing that helps create objects used for testing.

https://martinfowler.com/bliki/ObjectMother.html

**Comment by kcondon** [comment]
@MellyGray I keep seeing blank pages, even after trying the tricks: 

Sometimes I fix the blank page in Storybook by deleting the node_modules cache, from the dataverse-frontend/ root run:

rm -rf node_modules/.cache && npm i

If that doesn't work then maybe try deleting the whole node_modules folder:

rm -rf node_modules && npm i

**Comment by MellyGray** [comment]
@kcondon We can try troubleshooting in a zoom call after the standup

**Comment by kcondon** [comment]
@MellyGray Yes, maybe try after standup, thanks!

**Comment by kcondon** [comment]
@MellyGray Works well but the changed behavior of the checkbox selecting all on a page rather than all isn't in this -still selects all files.

**Comment by MellyGray** [comment]
> Works well but the changed behavior of the checkbox selecting all on a page rather than all isn't in this -still selects all files.

@kcondon I've merged the changes from 'develop' into this branch, so now the checkbox should work as expected here as well

**Pull request merged**
