### PR TITLE
Feature/420 Select Advanced (single and multiple selection with search)

### LINKED ISSUE #420: Select with Search in Design System & integrate in Dataset Metadata Form
## Overview of the Feature Request

We need to create a new select component, similar to our multiple select component but capable of choosing only one option.
The idea is to create a single component with search that works to select one or multiple options.

## What kind of user is the feature intended for?
SPA Users and Design System consumers.

## What inspired the request?
- While working on dataset form, we notice that there are Controlled Vocabulary fields that do have many options and in the JSF version instead of showing a normal native select a select with search is shown.

## What existing behavior do you want changed?
Instad of showing a native select, if a Controlled Vocabulary field has an specific amount of options, show a select with search field.

## Any brand new behavior do you want to add to Dataverse?
N/A

## Any open or closed issues related to this feature request?
N/A

### PR DESCRIPTION
**Pull request by GermanSaracca**
**What this PR does / why we need it**:
Adds a new Select component to the design system and integrates it into the EditDatasetMetadata form for multiple controlled vocabularies and for non-multiple controlled vocabularies when they have more than 10 options.

Removes `SelectMultiple` component, this `SelectAdvanced` component behaves as single or multiple selection.

**Which issue(s) this PR closes**:

Closes #420 

**Special notes for your reviewer**:

**Suggestions on how to test this**:
1. Execute `npm i`.
2. Navigate with `cd packages/design-system && npm run build`.
3. Execute `npm run storybook`
4. Test the SelectAdvanced component on Storybook on all of its modes:
- Single
- Multiple
- Single With Default Value
- Multiple With Default Value
- Single not Searchable
- Multiple not Seachable
- Invalid
- Disabled
- With Different Select Word (this only for single mode)
5. Also check the create dataset or edit dataset form and find a vocabulary not multiple field that has more than 10 options, instead of showing a native select it should show this `SelectAdvanced` component in single selection mode.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Yes.

**_SelectAdvanced on single mode with search._**
Screenshot 2024-07-01 at 10 25 16

**_SelectAdvanced on single mode without search._**
Screenshot 2024-07-01 at 10 25 26

**Is there a release notes update needed for this change?**:
N/A
**Additional documentation**:
N/A

### CODE REVIEW

**Comment by ekraffmiller** [comment]
Hi @GermanSaracca, it looks good!  I just wanted to check the behavior of the Single Select - it doesn't close the dropdown when an option is selected. Is that expected behavior?

https://github.com/user-attachments/assets/142d8b29-45f7-41eb-bb04-f46dc1653292

**Comment by GermanSaracca** [comment]
Hi @ekraffmiller, yes that is the expected behaviour, thanks!

**Comment by GermanSaracca** [comment]
@ekraffmiller change applied 👍🏼

**Review by ekraffmiller — APPROVED** [review]
Looks good, approved!

**Comment by GPortas** [comment]
@GermanSaracca Can you please resolve merge conflicts? Thanks!

**Comment by GermanSaracca** [comment]
@GPortas conflicts solved

**Review by GPortas — APPROVED** [review]
Works great in all modes

**Pull request merged**
