### PR TITLE
205 - Integration dataset user permissions

### LINKED ISSUE #205: Integration - Get dataset user permissions
## Overview of the Feature Request
Integrate getDatasetUserPermissions use case from the js-dataverse module with the Dataset SPA model to use the proper dataset permissions. Add e2e tests to check that the permissions are working as expected.

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- https://github.com/IQSS/dataverse-client-javascript/issues/96

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
Integrate the SPA with the js-dataverse implementation of the getDatasetUserPermissions  use case to get the dataset permissions

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-client-javascript/issues/96

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the integration of the SPA with the js-dataverse implementation to get the dataset user permissions

## Which issue(s) this PR closes:

- Closes #205 

## Special notes for your reviewer:

1. Not all of the dataset user permissions were integrated since there are still some changes needed in the API to get the canDownloadFiles and canManageFilesPermissions permissions
2. I added the friendlyType to correctly display the file types in the Files Table although it was not the purpose of this PR, but it was a change so small that it didn't make sense to create a separate issue for it.

### Step 1: Run the development environment
1. Run `npm I`
3. `cd packages/design-system && npm run build`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation

### Step 2: Test Dataset View mode with the implemented changes for the getFilesTotalDownloadSize
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset and publish it
5. From the dataset view mode copy the search parameters from the url. Ex.: `?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT`
6. Go to <http://localhost:8000/spa/datasets> and paste the search parameters. Ex.: <http://localhost:8000/spa/datasets?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT>
8. You are seeing now the same Dataset in the SPA. Try logging in and out to check that the different buttons with different permissions appear or disappear depending on the permissions

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No

## Is there a release notes update needed for this change?:
No

### CODE REVIEW

**Comment by GPortas** [comment]
@MellyGray Please, can you resolve the conflicts?

**Review by GPortas — COMMENTED** [review]
I'm having the following error while building the docker image, @MellyGray:

errpack

**Comment by MellyGray** [comment]
@GPortas  I followed the following steps and the docker image finished successfully:

`git checkout feature/205-integration-dataset-user-permissions`
`npm i`
`cd packages/design-system && npm run build && cd ../../`
`cd dev-env`
`./run-env.sh unstable`

I would clear npm cache and try again, I checked and that version exists in the npm registry so it shouldn't send a not found

**Comment by GPortas** [comment]
Works great!

**Unpublished dataset (Only draft version available):**

Logged in user:

draftlog

Guest user:

draftguest

**Published dataset:**

Logged in user:

publishedlog

Guest user:

publishedguest

**Pull request merged**
