### PR TITLE
30 - Add the design tokens of the design system

### LINKED ISSUE #30: Create the design tokens of the design system using SASS variables
## Overview of the Feature Request

We would like to add the design tokens of our design system to Storybook and to the code using SASS variables to make it easier for developers to reference and use these tokens in their projects. These design tokens are specified in the [Design System analysis document](https://docs.google.com/document/d/1OxCQO7B-yJaMWRl8EzuflcSmIaCmVSs19aoD83PjPmA/edit#heading=h.pjqhiu86e7l8).

## What kind of user is the feature intended for?

This feature is intended for developers who use Storybook to build and test components for our web application.

## What inspired the request?

Our design system includes a set of design tokens that define our brand colors, typography, spacing, and other styles. These tokens are used consistently across our applications to ensure a cohesive and polished user experience. However, developers currently have to manually reference these tokens in their code, which can be time-consuming and error-prone. By adding the design tokens with SASS variables and document them in the Storybook, we can provide a centralized and easy-to-use reference for developers.

Some references for the Storybook:

- [Vibe Design System](https://style.monday.com/?path=/docs/foundations-colors--page)
- [Storybook Design System](https://storybook-design-system.netlify.app/?path=/docs/colors--page)
- [More references](https://storybook.js.org/showcase)

## What existing behavior do you want changed?

We want to add a new section to Storybook that displays our design tokens in a clear and organized way. This section should include documentation on how to use each token, as well as examples of how the tokens can be applied to different components. This tokens would be used in the scss files using SASS variables. 

## Any brand new behavior do you want to add to Dataverse?

No, this feature request does not introduce any brand new behavior to Dataverse.

## Any open or closed issues related to this feature request?

- https://github.com/IQSS/dataverse-frontend/issues/14

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:

This PR adds the Design Tokens of the design system to used across the application as described in the [Design System Analysis Doc](https://docs.google.com/document/d/1OxCQO7B-yJaMWRl8EzuflcSmIaCmVSs19aoD83PjPmA/edit#heading=h.pjqhiu86e7l8). We need this design tokens to use them consistently across the application so they are declared in one placed and applied everywhere. Design Tokens are like enums of typography and color.

Also, I added a ThemeProvider to apply these design tokens to the whole application thinking about using this ThemeProvider in the future as a way to customizing the installation.

## Which issue(s) this PR closes:

- Closes #30 

## Special notes for your reviewer:
I added the ThemeProvider to set the design tokens in the whole application. But at the same time I was having in mind that we could allow in the future to change these design tokens to customize the installation, but then in that case we would bring the overrided variables from React into SASS instead of the other way around as it is right now. That would be much work so I'll let that for the future when we are thinking about customization but since all the react code is reading these variables, we'll just need to change the config but not the developed components.

For the semantic colors I had to change the default Bootrstrap colors because they were not passing the accessibility tests. They have a [note about this in Bootstrap docs](https://getbootstrap.com/docs/5.0/components/badge/#background-colors)

image

These are the final colors passing the tests
image

## Suggestions on how to test this:

`npm run storybook`

Go to http://localhost:6006

There is a new section called Design Tokens were you can find 2 new files, the Colors and Typography. These docs represents the tokens. 

You can also go to src/sections/ui/assets/styles/design-tokens/colors.module.scss or src/sections/ui/assets/styles/design-tokens/typography.module.scss to modify the design tokens to see how they change in the whole application using the Storybook to visualise this change

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
None

## Is there a release notes update needed for this change?:
Design Tokens added to the design system

## Additional documentation:
- [ThemeProvider and Design Tokens](https://javascript.plainenglish.io/theming-components-with-react-and-bit-456fca5d537b)

### CODE REVIEW

**Comment by mreekie** [comment]
grooming
- Melly thanks for re-sizing what's left this for the new Sprint!

**Comment by MellyGray** [comment]
> grooming
> 
> * Melly thanks for re-sizing what's left this for the new Sprint!

@mreekie ups, actually it should be a 3

**Comment by kcondon** [comment]
@MellyGray This looks good but there is a merge conflict that needs to be resolved.

**Comment by MellyGray** [comment]
@kcondon fixed now!

**Pull request merged**
