### PR TITLE
TransferList component

### LINKED ISSUE #449: TransferList Component
We need to create this Transfer List component to be used in the **_Browse/Search Facets_** section on the Create/Edit Collection page.

Screenshot 2024-07-31 at 12 19 15

### PR DESCRIPTION
**Pull request by GermanSaracca**
**What this PR does / why we need it**:
Adds new TransferList component to the Design System.
I have used packages from the [dnd-kit](https://docs.dndkit.com/) library to achieve the sorting through drag and drop.

**Which issue(s) this PR closes**:

Closes #449 

**Special notes for your reviewer**:

**Suggestions on how to test this**:
Check the documentation of the component on Storybook.
Check and try the different stories and see the logs on the dev tools console.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:

https://github.com/user-attachments/assets/023fea7f-131e-40e0-b9b9-afcd3ca6f72a

**Is there a release notes update needed for this change?**:
N/A

**Additional documentation**:
N/A

### CODE REVIEW

**Review by ekraffmiller — COMMENTED** [review]
This looks good! The only thing I noticed is that if you check items on one side, then select them all to be moved, the checks are still there on the other side, is that intended behavior?

https://github.com/user-attachments/assets/30be7c17-4c54-4f5b-a832-ea11134670d8

**Comment by GermanSaracca** [comment]
@ekraffmiller  Yes, that is indeed the expected behaviour.
I can change it, but I thought about leaving it since normally if you check the checboxes it is because you don't want to transfer them all, so if you unintentionally transfer them all, you can transfer them all back to the left and your original selection will be kept so that you can only transfer the selected ones again if you want to.

**Comment by ekraffmiller** [comment]
> @ekraffmiller Yes, that is indeed the expected behaviour. I can change it, but I thought about leaving it since normally if you check the checboxes it is because you don't want to transfer them all, so if you unintentionally transfer them all, you can transfer them all back to the left and your original selection will be kept so that you can only transfer the selected ones again if you want to.

Ok, I hadn't thought of that, but it makes sense! thanks

**Review by ekraffmiller — APPROVED** [review]
Looks good to me!

**Review by GPortas — DISMISSED** [review]
Works great!

**Comment by GPortas** [comment]
@GermanSaracca Can you resolve merge conflicts? And I will merge after that. Thanks!

**Comment by GermanSaracca** [comment]
@GPortas done!

**Review by GPortas — APPROVED** [review]

**Pull request merged**
