### PR TITLE
Feature/355 select multiple component

### LINKED ISSUE #355: Create Select multiple component for the design system
We should create a multiple select with search as well as the one that exists in JSF for multiple vocabulary fields.
The scope of this ticket should aim to just create the component within the design system and make it look as similar as possible to the rest of the components.

**_Notes:_**
- ~~We could use a very popular and widely used library called [React-Select](https://react-select.com/home)~~

**_Update_**
Not using react-select library now, see [comment](https://github.com/IQSS/dataverse-frontend/issues/355#issuecomment-2066577227)

Create the component from scratch, without external libraries and make it according to our needs as in the JSF version
Screenshot 2024-04-19 at 09 17 30

### PR DESCRIPTION
**Pull request by GermanSaracca**
**What this PR does / why we need it**:
Adds new Select Multiple component to the Design System.

**Which issue(s) this PR closes**:
Closes #355 

**Special notes for your reviewer**:
Also export some form elements interfaces to solve a ts errors issue when building the design system about FormGroup trying to access private types.
Also add props to existent Select component.

**Suggestions on how to test this**:

Test the component in storybook.
Check [Isolated Select Multiple component](https://646fbe232a8d3b501a1943f3-wagrtclujo.chromatic.com/?path=/story/select-multiple--default) in Storybook

Check [Select Multiple component within a form](https://646fbe232a8d3b501a1943f3-wagrtclujo.chromatic.com/?path=/story/form--select-multiple) in Storybook.

**Does this PR introduce a user interface change? If mockups are available, please link/include them here**:
Screenshot 2024-04-29 at 14 43 10

**Is there a release notes update needed for this change?**:
CHANGELOG in the Design System package has been updated.

**Additional documentation**:
No.

### CODE REVIEW

**Review by ekraffmiller — COMMENTED** [review]
This looks really good!  I don't have any requested changes in the code, but I noticed a behavior in the Story that I think could be improved.  When you type in the search to get a subset of items, then click the select all checkbox, it selects all the items in the list, not just what you selected, which seems a little unexpected.
For example: 

https://github.com/IQSS/dataverse-frontend/assets/675224/88af2905-eeb1-4d48-a5ee-cf432e2b0370

**Review by ekraffmiller — APPROVED** [review]
looks good! approved!

**Review by GPortas — COMMENTED** [review]
I'm facing the same error that @ekraffmiller initially detected. When I select all items based on a query string, all items without filter are selected. This happens in both stories.

https://github.com/IQSS/dataverse-frontend/assets/17010447/98801359-6b7d-45d9-9bba-c7cfc8509468

https://github.com/IQSS/dataverse-frontend/assets/17010447/c41aecfa-2b84-4648-b4ab-cb3267e82c94

**Comment by GermanSaracca** [comment]
Hi @GPortas , the initial storybooks links from the PR description are outdated, they have the code before the changes requested by @ekraffmiller.
Here is the [last storybook build with the latest changes](https://646fbe232a8d3b501a1943f3-xswslbzmah.chromatic.com/?path=/story/select-multiple--default), please review it here.
I was really convinced that action of chromatic deployment running on same PR was going to replace latest build on the same url than before.

**Pull request merged**
