### PR TITLE
311 - Integrate breadcrumbs with owner information

### LINKED ISSUE #311: Integrate breadcrumbs with new owner information in js-dataverse
## Overview of the Feature Request

Display the actual breadcrumb routes from the new owner info added in https://github.com/IQSS/dataverse-client-javascript/issues/122

This issues depends on:
https://github.com/IQSS/dataverse-client-javascript/issues/122

## What kind of user is the feature intended for?
All of them

## What inspired the request?
- https://github.com/IQSS/dataverse-client-javascript/issues/123

## What existing behavior do you want changed?
None

## Any brand new behavior do you want to add to Dataverse?
Integrate breadcrumbs with new owner information in js-dataverse

## Any open or closed issues related to this feature request?
- https://github.com/IQSS/dataverse-client-javascript/issues/122
- https://github.com/IQSS/dataverse/pull/10322

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
Display the actual breadcrumb routes from the new owner info recently added to the Dataverse API

This issue depends on:
- https://github.com/IQSS/dataverse-client-javascript/issues/122
- https://github.com/IQSS/dataverse-client-javascript/issues/121

## Which issue(s) this PR closes:

- Closes #311 

## Special notes for your reviewer:
I changed the Home page to be the collection page since now we're able to display datasets from collections different than the root one.

The e2e tests are failing because the GitHub Action is using an unstable image of Dataverse instead of the image containing the necessary Dataverse changes. The Dataverse branch should be merged prior to this one

### Step 1: Run the development environment
1. Run `npm I`
3. `cd packages/design-system && npm run build`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh unstable`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation

### Step 2: Test breadcrumbs
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataverse collection
4. Create a new Dataset
5. Upload a file to the dataset
7. Go to <http://localhost:8000/spa> and select your dataset in the list
8. From the list of files in the Dataset page select your file to go to the File page
9. Now from the File page check the breadcrumbs are being displayed correctly and click the corresponding dataset breadcrumb
10. Now you should be in the Dataset Page. Look at the breadcrumbs and click the collection link
11. Now you should be in the Collection view. Now click on the Root breadcrumb to go to the initial page

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No

## Is there a release notes update needed for this change?:
Add breadcrumbs navigation to the SPA

### CODE REVIEW

**Comment by GPortas** [comment]
@MellyGray Can you please resolve the conflicts?

**Review by GPortas — COMMENTED** [review]
I am getting this error when accessing the dataset page. It happens both from the home page and by manually typing the URL.

@MellyGray 

Captura de Pantalla 2024-02-28 a las 16 26 07

**Review by GPortas — CHANGES_REQUESTED** [review]
I created the following hierarchy to test breadcrumbs:

_Root > Dataverse 1 > Dataverse 2 > Test Dataset > Test File_

File page breadcrumbs work as expected:

filebr

Dataset page breadcrumbs work as expected:

datasetbr

But the collection page for "Dataverse 2" is missing "Dataverse 1" as parent. Also, it is showing the display name as "Dataverse-2", including a dash in the name:

dvbr

**Comment by MellyGray** [comment]
> But the collection page for "Dataverse 2" is missing "Dataverse 1" as parent. Also, it is showing the display name as "Dataverse-2", including a dash in the name:
> 
> dvbr

We haven't started working in the Collection page so there's no use case in js-dataverse to get the collection, that's why the title and the breadcrumbs are not coming from the API. We can create some issues to start working on the Collection page

I added the fix for the enum switch, thanks!

**Review by GPortas — APPROVED** [review]
LGTM

**Pull request merged**
