### PR TITLE
10 - Migrate to Vite

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:

This PR migrates the SPA from Create React App to Vite. Vite seems to have a brighter future than Create React App.

## Which issue(s) this PR closes:

[Closes https://github.com/IQSS/dataverse-frontend/issues/3](https://github.com/IQSS/dataverse-frontend/issues/10)

#### Create React App replaced by Vite
The migration of the main application went really smooth. The difficulties came from the testing frameworks, Jest and Cypress, and from the Storybook, since all of them were using webpack.

#### Jest replaced by Vitest
[Jest support for ES Modules is experimental](https://jestjs.io/docs/ecmascript-modules) so the implementation has bugs and lack features. There is a plugin for Vite [vite-jest](https://github.com/sodatea/vite-jest/blob/main/packages/vite-jest/README.md) but it's still work in progress and it doesn't support Windows.

So my decision was to migrate from Jest to [Vitest](https://vitest.dev) which also has support for Testing Library and Storybook. The migration went really smooth since the syntax is the same as with Jest and it uses the same `vite.config.ts` file to run Vite.

#### Cypress migration
To migrate Cypress I just configured the plugin for Vite [cypress-vite](https://github.com/mammadataei/cypress-vite) and the migration went really smooth except for TypeScript. 

TypeScript gave me a lot of issues because the `.spec.ts` files from Cypress aren't modules. This was fixed changing the tsconfig.json files

#### Storybook updated to version 7 for a first-class Vite support
Storybook 6 was being used in the current application but it doesn't support Vite. There is a plugin [builder-vite](https://github.com/storybookjs/builder-vite) but it only supports Node 14-16. 

So the decision was to downgrade the Node version or to migrate to [Storybook 7](https://storybook.js.org/blog/7-0-beta/) which will be released on March 14th.

I decided to migrate to Storybook 7 since we are really close to the release date.

The migration files didn't worked for me and I had to remove the whole storybook and install it from the beginning.

## Suggestions on how to test this:

Remove `/build` folder if it exists in your root directory, since it is the old build from Create React App

Run `rm -rf node_modules` to delete any dependency installed that could conflict with the migration

Run `npm install`

Run `npm start` to see the application running on localhost. 

Run `npm test` to run the unit tests with Vitest

Run `npm run cy:run` to run the e2e tests with Cypress

Run `npm run storybook` to run the Storybook on localhost

Run `npm run test-storybook` to run the tests on the Storybook

For more scripts see the README

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:

None

## Is there a release notes update needed for this change?:

Vite integration

## Additional documentation:

[Dataverse - SPA Development Strategy](https://docs.google.com/document/d/1vOSsIGGCbgal4f_lSp1yInQifBcmo5vZ-Z9pfkVDyG4/edit#heading=h.mv60u03m9o2a)

### CODE REVIEW

**Review by rtreacy — APPROVED** [review]
Nice job! I have been looking at incremental changes since this morning - npm install is really Vite(fast)!

**Review by pdurbin — COMMENTED** [review]
This is really looking good! `npm start` seems much faster! 🎉 🚀 

I'm very happy with this new, stronger foundation. Thanks, @MellyGray!!

@MellyGray I did have one question about potential cruft leftover from when you removed Jest. Details are here: https://github.com/IQSS/dataverse-frontend/pull/11#issuecomment-1454140718 . Thanks.

**Comment by rtreacy** [comment]
https://markus.oberlehner.net/blog/using-testing-library-jest-dom-with-vitest/

**Comment by kcondon** [comment]
The tests pass, built and deployed to S3. I'm ok with merging as incrementally better and can raise cruft issue at Monday's meeting.

**Comment by rtreacy** [comment]
I put this back in Ready for QA

**Comment by kcondon** [comment]
The tests pass, built and deployed to S3. I'm ok with merging as incrementally better and can raise cruft issue at Monday's meeting.

**Comment by MellyGray** [comment]
> 
> Here are the hits in files other than package-lock.json (where there are lots of hits):
> 
> ```
> $ ack -i jest tests/setupTests.ts package.json .eslintrc.json 
> tests/setupTests.ts
> 1:// jest-dom adds custom jest matchers for asserting on DOM nodes.
> 4:// learn more: https://github.com/testing-library/jest-dom
> 5:import '@testing-library/jest-dom'
> 
> package.json
> 10:    "@testing-library/jest-dom": "^5.16.5",
> 
> .eslintrc.json
> 15:    "jest": true,
> ```
> 

I may have forgotten to remove some unused jest refererences, thank you for reporting it!

For `tests/setupTests.ts` as @rtreacy said `@testing-library/jest-dom` is still needed for using Testing Library, Vitest even have an [example repo using this dependency ](https://github.com/vitest-dev/vitest/blob/main/examples/react-testing-lib/package.json)

> .eslintrc.json
> 15:    "jest": true,

We should remove this reference, if Vitests globals have conflicts with ESlint we can fix it when that problem arises, right now `npm run lint` seems to be working fine without `"jest": true,`

> package-lock.json

I've been checking and some jest references come from `@testing-library/jest-dom` and others come from `@storybook/test-runner` so I think is not possible to remove the jest references from this file


**Then I think we only need to remove `"jest": true,` from `.eslintrc.json` . Should we create an issue for this or just remember to remove it in the next feature? @pdurbin**

**Comment by pdurbin** [comment]
@MellyGray thanks for the detailed response. I don't think we need a dedicated issue or pull request for removing any Jest cruft. Perhaps it can happen on any future pull request. Thanks.

**Pull request merged**
