### PR TITLE
172 - Integration add FileCriteria to the getFilesCountInfo use case

### LINKED ISSUE #172: [Spike - Integration/Front] Add FileCriteria to the getFilesCountInfo use case
## Overview of the Feature Request

In this issue #168 we have integrated the file counts use case from js-dataverse, but without the FileCriteria used to filter the files results.

We need to add this FileCriteria argument to the getFilesCountInfo use case connected to the UI and also add the integration of this extra argument with it's js-dataverse implementation.

## What kind of user is the feature intended for?

All users

## What inspired the request?

- #168

In this issue #168 we integrated the file counts use case from js-dataverse, but without the FileCriteria used to filter the files results. We need this extra argument to be taken into account to correctly display the file counts in the Files Table UI, when filters or search are applied

## What existing behavior do you want changed?

None

## Any brand new behavior do you want to add to Dataverse?

Display the correct file counts in the Files Table, when filters or search are applied.

## Any open or closed issues related to this feature request?
- #168

### PR DESCRIPTION
**Pull request by MellyGray**
## What this PR does / why we need it:
This PR adds the FileCriteria to the  getFilesCountInfo use case, so the files count takes into account the filters and search applied to get the files.

## Which issue(s) this PR closes:

- Closes #172 

## Special notes for your reviewer:
The e2e tests for the getFilesTotalDownloadSizeByDatasetPersistentId won't work because these PR need to be merged https://github.com/IQSS/dataverse/pull/9960

### Step 1: Run the development environment
1. Run `npm I`
3. `cd packages/design-system && npm run build`
4. `cd ../../`
5. Check that you have a  `.env` file such as the .env.example, with the `VITE_DATAVERSE_BACKEND_URL=http://localhost:8000` variable
6.  `cd dev-env`
7. `./run-env.sh 9907-file-counts-with-criteria`
8. To check the environment go to <http://localhost:8000> and check your local dataverse installation

### Step 2: Test Dataset View mode with the implemented changes for the getFilesCountInfo
1. Go to <http://localhost:8000>
2. Login as admin using username: dataverseAdmin and password: admin1
3. Create a new Dataset
4. Upload some files with different types, or tags, or access.
5. From the dataset view mode copy the search parameters from the url. Ex.: `?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT`
6. Go to <http://localhost:8000/spa/datasets> and paste the search parameters. Ex.: <http://localhost:8000/spa/datasets?persistentId=doi:10.5072/FK2/LHGRHP&version=DRAFT>
8. You are seeing now the same Dataset in the SPA, check that when you apply some filter to the Files Table, the filters dropdown options are updated with the new available filters after narrowing the search.

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
No

## Is there a release notes update needed for this change?:
No

### CODE REVIEW

**Comment by GPortas** [comment]
Same building error here! Can you check other PRs? @MellyGray 

errbuild

**Review by GPortas — COMMENTED** [review]
In addition to the already known e2e error, we have a component test error: 

https://github.com/IQSS/dataverse-frontend/actions/runs/6668791789/job/18125143989?pr=196

The functionality works as expected. We can see how the file type counts are updated here after selecting public access. The .yml file is restricted.

countsgif

**Comment by MellyGray** [comment]
@GPortas I fixed the unit tests and there is an opened issue to fix the e2e

**Comment by GPortas** [comment]
We have a build error in develop when deploying to beta testing:

https://github.com/IQSS/dataverse-frontend/actions/runs/6731104689/job/18295128987

It seems related to storybook. If it's not too big, can we make the fix in this PR to stabilize develop? @MellyGray

**Comment by MellyGray** [comment]
@GPortas I fixed the Storybook error, I think that should fix beta

**Pull request merged**
