### PR TITLE
Feature/294 clear test datasets

### LINKED ISSUE #294: Clear test datasets before integration test
When the integration tests cause a build up of datasets in Dataverse, then calling destroyAll() before the "gets the total dataset count" test in DatasetJSDataverseRepository.spec.ts causes an optimistic lock exception in Dataverse.

To avoid having a large number of datasets to delete all at once, we can add destroyAll() to the beforeEach method of integration tests. 
Here is an example of the test failure:
https://github.com/IQSS/dataverse-frontend/actions/runs/7653145563/job/20968488247

### PR DESCRIPTION
**Pull request by ekraffmiller**
## What this PR does / why we need it:
Deletes test datasets before e2e tests, so that destroyAll() doesn't fail when trying to delete too many tests at once.

## Which issue(s) this PR closes:

- Closes #294

## Suggestions on how to test this:
Run the e2e tests, check that test datasets have been deleted after the tests run. Check that "gets the total dataset count" test in DatasetJSDataverseRepository.spec.ts runs without errors

## Does this PR introduce a user interface change? If mockups are available, please link/include them here:
no

### CODE REVIEW

**Review by MellyGray — CHANGES_REQUESTED** [review]
We're also creating datasets in the `FileJSDataverseRepository.spec.ts` and `Collection.spec.tsx` files. We should include the `destroyAll` method there as well.

Additionally, since we're now destroying all datasets at the beginning of each test, we should consider removing all calls to the `destroyAll` method within the individual tests. Such as in `cy.wrap(DatasetHelper.destroyAll().then(() => DatasetHelper.createWithTitle(title)))`

**Comment by ekraffmiller** [comment]
thanks @MellyGray, I made the changes you suggested

**Review by MellyGray — DISMISSED** [review]
LGTM!

**Comment by GermanSaracca** [comment]
Hi @ekraffmiller , 2 suites of tests are failing, I attach screenshots.
I removed images and volumes from docker, downloaded everything again and they are still occurring in the same way.
Screenshot 2024-04-03 at 09 22 03
Screenshot 2024-04-03 at 08 54 04
Screenshot 2024-04-03 at 09 21 01

**Comment by ekraffmiller** [comment]
@GermanSaracca I tried it again locally, as well as re-running the action, and I haven't reproduced the errors. I think it must be a timing issue. One thing that may be different is the Docker settings.  A while ago, I had to increase my resource settings in Docker, in order to run other containers.  Here is what I have for Docker resources:
Screenshot 2024-04-03 at 11 57 35 AM
Can you check what you have, and maybe try running again with more memory?

**Comment by GermanSaracca** [comment]
I unassign me from possible local environment problems to test this issue. Looks like a timing issue on my end.
@MellyGray @GPortas could any of you test this on your end?

**Review by GPortas — COMMENTED** [review]
@ekraffmiller Can you please resolve the merge conflicts?

**Review by GPortas — APPROVED** [review]

**Pull request merged**
